[debug] [2025-08-26T01:11:46.807Z] [Firebase Plugin] Activating Firebase extension.
[debug] [2025-08-26T01:11:47.507Z] [Firebase Plugin] requireAuthWrapper
[debug] [2025-08-26T01:11:47.508Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2025-08-26T01:11:47.509Z] > authorizing via signed-in user (ayi198701@gmail.com)
[debug] [2025-08-26T01:11:47.516Z] Checked if tokens are valid: false, expires at: 1756157335805
[debug] [2025-08-26T01:11:47.516Z] Checked if tokens are valid: false, expires at: 1756157335805
[debug] [2025-08-26T01:11:47.516Z] > refreshing access token with scopes: []
[debug] [2025-08-26T01:11:47.518Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2025-08-26T01:11:47.518Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2025-08-26T01:11:47.528Z] [Firebase Plugin] VSCode notification server listening on port 40001
[info] [Firebase Plugin] Starting Data Connect toolkit (version 2.11.2) on port 50001
[debug] [2025-08-26T01:11:47.898Z] 'fdc build' failed with error: Unable to build your Data Connect schema and connectors (exit code 1): E0826 09:11:47.890357    3824 cmd.go:43] Error loading data connect config: could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"'fdc build' failed with error: Unable to build your Data Connect schema and connectors (exit code 1): E0826 09:11:47.890357    3824 cmd.go:43] Error loading data connect config: could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:11:47.899Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"dataconnect"},"message":"Ignoring unsupported arg: auto_download"}}
[debug] [2025-08-26T01:11:47.899Z] Ignoring unsupported arg: port {"metadata":{"emulator":{"name":"dataconnect"},"message":"Ignoring unsupported arg: port"}}
[debug] [2025-08-26T01:11:47.899Z] Starting Data Connect Emulator with command {"binary":"C:\\Users\\Administrator\\.cache\\firebase\\emulators\\dataconnect-emulator-2.11.2.exe","args":["--logtostderr","-v=2","dev","--listen=localhost:50001","--config_dir=d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect","--enable_output_schema_extensions=true","--enable_output_generated_sdk=true"],"optionalArgs":["listen","config_dir","enable_output_schema_extensions","enable_output_generated_sdk"],"joinArgs":true,"shell":false,"port":9399} {"metadata":{"emulator":{"name":"dataconnect"},"message":"Starting Data Connect Emulator with command {\"binary\":\"C:\\\\Users\\\\Administrator\\\\.cache\\\\firebase\\\\emulators\\\\dataconnect-emulator-2.11.2.exe\",\"args\":[\"--logtostderr\",\"-v=2\",\"dev\",\"--listen=localhost:50001\",\"--config_dir=d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\",\"--enable_output_schema_extensions=true\",\"--enable_output_generated_sdk=true\"],\"optionalArgs\":[\"listen\",\"config_dir\",\"enable_output_schema_extensions\",\"enable_output_generated_sdk\"],\"joinArgs\":true,\"shell\":false,\"port\":9399}"}}
[info] i  dataconnect: Data Connect Emulator logging to dataconnect-debug.log {"metadata":{"emulator":{"name":"dataconnect"},"message":"Data Connect Emulator logging to \u001b[1mdataconnect-debug.log\u001b[22m"}}
[debug] [2025-08-26T01:11:47.933Z] E0826 09:11:47.929742    3600 dev.go:79] Failed to load initial config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:11:47.929742    3600 dev.go:79] Failed to load initial config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:11:47.934Z] E0826 09:11:47.934742    3600 watch.go:102] watchAllDir unable to walk dir `d:\xiangmu\Edge-Function\ctoapp\dataconnect`: CreateFile d:\xiangmu\Edge-Function\ctoapp\dataconnect: The system cannot find the file specified.
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:11:47.934742    3600 watch.go:102] watchAllDir unable to walk dir `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`: CreateFile d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect: The system cannot find the file specified.\n"}}
[debug] [2025-08-26T01:11:47.940Z] I0826 09:11:47.940742    3600 dev.go:102] Listening on address (HTTP + gRPC): 127.0.0.1:50001
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"I0826 09:11:47.940742    3600 dev.go:102] Listening on address (HTTP + gRPC): 127.0.0.1:50001\n"}}
[error] [Firebase Plugin] error:  {}
[debug] [2025-08-26T01:11:48.309Z] <<< [apiv2][status] POST https://www.googleapis.com/oauth2/v3/token 200
[debug] [2025-08-26T01:11:48.309Z] <<< [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2025-08-26T01:11:48.318Z] [Firebase Plugin] User found:  ayi198701@gmail.com
[info] [Firebase Plugin] (Core:Project) New user detected, fetching projects
[debug] [2025-08-26T01:11:48.319Z] Checked if tokens are valid: true, expires at: 1756174307310
[debug] [2025-08-26T01:11:48.320Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects pageSize=1000
[debug] [2025-08-26T01:11:49.328Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects 200
[debug] [2025-08-26T01:11:49.330Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects [omitted]
[debug] [2025-08-26T01:11:57.953Z] E0826 09:11:57.953611    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:11:57.953611    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:12:07.935Z] E0826 09:12:07.936267    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:12:07.936267    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:12:17.935Z] E0826 09:12:17.936562    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:12:17.936562    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:12:27.935Z] E0826 09:12:27.936534    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:12:27.936534    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:12:37.935Z] E0826 09:12:37.935321    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:12:37.935321    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:12:47.935Z] E0826 09:12:47.935562    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:12:47.935562    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:12:57.935Z] E0826 09:12:57.936458    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:12:57.936458    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:13:07.935Z] E0826 09:13:07.936117    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:13:07.936117    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:13:17.935Z] E0826 09:13:17.935917    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:13:17.935917    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:13:27.936Z] E0826 09:13:27.936334    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:13:27.936334    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:13:37.936Z] E0826 09:13:37.936149    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:13:37.936149    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:13:47.936Z] E0826 09:13:47.936089    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:13:47.936089    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:13:47.937Z] E0826 09:13:47.936089    3600 watch.go:102] watchAllDir unable to walk dir `d:\xiangmu\Edge-Function\ctoapp\dataconnect`: CreateFile d:\xiangmu\Edge-Function\ctoapp\dataconnect: The system cannot find the file specified.
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:13:47.936089    3600 watch.go:102] watchAllDir unable to walk dir `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`: CreateFile d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect: The system cannot find the file specified.\n"}}
[debug] [2025-08-26T01:13:57.936Z] E0826 09:13:57.937234    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:13:57.937234    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:14:07.936Z] E0826 09:14:07.936780    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:14:07.936780    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:14:17.935Z] E0826 09:14:17.936821    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:14:17.936821    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:14:27.937Z] E0826 09:14:27.937026    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:14:27.937026    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:14:37.938Z] E0826 09:14:37.938204    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:14:37.938204    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:14:47.937Z] E0826 09:14:47.936819    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:14:47.936819    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:14:57.938Z] E0826 09:14:57.938316    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:14:57.938316    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:15:07.937Z] E0826 09:15:07.938263    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:15:07.938263    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:15:17.937Z] E0826 09:15:17.937558    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:15:17.937558    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:15:27.938Z] E0826 09:15:27.938035    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:15:27.938035    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:15:37.937Z] E0826 09:15:37.937481    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:15:37.937481    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:15:47.937Z] E0826 09:15:47.937715    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
E0826 09:15:47.938802    3600 watch.go:102] watchAllDir unable to walk dir `d:\xiangmu\Edge-Function\ctoapp\dataconnect`: CreateFile d:\xiangmu\Edge-Function\ctoapp\dataconnect: The system cannot find the file specified.
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:15:47.937715    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\nE0826 09:15:47.938802    3600 watch.go:102] watchAllDir unable to walk dir `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`: CreateFile d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect: The system cannot find the file specified.\n"}}
[debug] [2025-08-26T01:15:57.937Z] E0826 09:15:57.938167    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:15:57.938167    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:16:07.937Z] E0826 09:16:07.938398    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:16:07.938398    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:16:17.938Z] E0826 09:16:17.938859    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:16:17.938859    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:16:27.937Z] E0826 09:16:27.937823    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:16:27.937823    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:16:37.938Z] E0826 09:16:37.938948    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:16:37.938948    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:16:47.938Z] E0826 09:16:47.938613    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:16:47.938613    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:16:57.938Z] E0826 09:16:57.938533    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:16:57.938533    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:17:07.938Z] E0826 09:17:07.938258    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:17:07.938258    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:17:17.938Z] E0826 09:17:17.938633    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:17:17.938633    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:17:27.939Z] E0826 09:17:27.939119    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:17:27.939119    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:17:37.939Z] E0826 09:17:37.938799    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:17:37.938799    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:17:47.938Z] E0826 09:17:47.938600    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
E0826 09:17:47.938600    3600 watch.go:102] watchAllDir unable to walk dir `d:\xiangmu\Edge-Function\ctoapp\dataconnect`: CreateFile d:\xiangmu\Edge-Function\ctoapp\dataconnect: The system cannot find the file specified.
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:17:47.938600    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\nE0826 09:17:47.938600    3600 watch.go:102] watchAllDir unable to walk dir `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`: CreateFile d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect: The system cannot find the file specified.\n"}}
[debug] [2025-08-26T01:17:57.939Z] E0826 09:17:57.938856    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:17:57.938856    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:18:07.940Z] E0826 09:18:07.941224    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:18:07.941224    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:18:17.939Z] E0826 09:18:17.940277    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:18:17.940277    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:18:27.938Z] E0826 09:18:27.939216    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:18:27.939216    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:18:37.939Z] E0826 09:18:37.939474    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:18:37.939474    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:18:47.939Z] E0826 09:18:47.939433    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:18:47.939433    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:18:57.939Z] E0826 09:18:57.939950    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:18:57.939950    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:19:07.940Z] E0826 09:19:07.940107    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:19:07.940107    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:19:17.939Z] E0826 09:19:17.939851    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:19:17.939851    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:19:27.938Z] E0826 09:19:27.939662    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:19:27.939662    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:19:37.940Z] E0826 09:19:37.939726    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:19:37.939726    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:19:47.940Z] E0826 09:19:47.940037    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
E0826 09:19:47.940037    3600 watch.go:102] watchAllDir unable to walk dir `d:\xiangmu\Edge-Function\ctoapp\dataconnect`: CreateFile d:\xiangmu\Edge-Function\ctoapp\dataconnect: The system cannot find the file specified.
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:19:47.940037    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\nE0826 09:19:47.940037    3600 watch.go:102] watchAllDir unable to walk dir `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`: CreateFile d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect: The system cannot find the file specified.\n"}}
[debug] [2025-08-26T01:19:57.940Z] E0826 09:19:57.940690    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:19:57.940690    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:20:07.940Z] E0826 09:20:07.940247    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:20:07.940247    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:20:17.941Z] E0826 09:20:17.940861    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:20:17.940861    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:20:27.940Z] E0826 09:20:27.940581    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:20:27.940581    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:20:37.942Z] E0826 09:20:37.942432    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:20:37.942432    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:20:47.940Z] E0826 09:20:47.940600    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:20:47.940600    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:20:57.940Z] E0826 09:20:57.940744    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:20:57.940744    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:21:07.940Z] E0826 09:21:07.940841    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:21:07.940841    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:21:17.941Z] E0826 09:21:17.941549    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:21:17.941549    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:21:27.940Z] E0826 09:21:27.941648    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:21:27.941648    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:21:37.941Z] E0826 09:21:37.941039    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:21:37.941039    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:21:47.941Z] E0826 09:21:47.941216    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
E0826 09:21:47.941216    3600 watch.go:102] watchAllDir unable to walk dir `d:\xiangmu\Edge-Function\ctoapp\dataconnect`: CreateFile d:\xiangmu\Edge-Function\ctoapp\dataconnect: The system cannot find the file specified.
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:21:47.941216    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\nE0826 09:21:47.941216    3600 watch.go:102] watchAllDir unable to walk dir `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`: CreateFile d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect: The system cannot find the file specified.\n"}}
[debug] [2025-08-26T01:21:57.941Z] E0826 09:21:57.941801    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:21:57.941801    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:22:07.941Z] E0826 09:22:07.941742    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:22:07.941742    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:22:17.941Z] E0826 09:22:17.942332    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:22:17.942332    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:22:27.941Z] E0826 09:22:27.941662    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:22:27.941662    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:22:37.942Z] E0826 09:22:37.942573    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:22:37.942573    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:22:47.942Z] E0826 09:22:47.942233    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:22:47.942233    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:22:57.942Z] E0826 09:22:57.941996    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:22:57.941996    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:23:07.942Z] E0826 09:23:07.942888    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:23:07.942888    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:23:17.943Z] E0826 09:23:17.943141    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:23:17.943141    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:23:27.942Z] E0826 09:23:27.942776    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:23:27.942776    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:23:37.942Z] E0826 09:23:37.942342    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:23:37.942342    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:23:47.943Z] E0826 09:23:47.942623    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:23:47.942623    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:23:47.944Z] E0826 09:23:47.943674    3600 watch.go:102] watchAllDir unable to walk dir `d:\xiangmu\Edge-Function\ctoapp\dataconnect`: CreateFile d:\xiangmu\Edge-Function\ctoapp\dataconnect: The system cannot find the file specified.
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:23:47.943674    3600 watch.go:102] watchAllDir unable to walk dir `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`: CreateFile d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect: The system cannot find the file specified.\n"}}
[debug] [2025-08-26T01:23:57.942Z] E0826 09:23:57.942641    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:23:57.942641    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:24:07.942Z] E0826 09:24:07.942734    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:24:07.942734    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:24:17.960Z] E0826 09:24:17.943567    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:24:17.943567    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:24:27.943Z] E0826 09:24:27.944381    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:24:27.944381    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:24:37.944Z] E0826 09:24:37.943770    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:24:37.943770    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:24:47.943Z] E0826 09:24:47.943272    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:24:47.943272    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:24:57.943Z] E0826 09:24:57.943513    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:24:57.943513    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:25:07.943Z] E0826 09:25:07.943580    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:25:07.943580    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:25:17.944Z] E0826 09:25:17.944275    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:25:17.944275    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:25:27.944Z] E0826 09:25:27.944253    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:25:27.944253    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:25:37.944Z] E0826 09:25:37.944095    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:25:37.944095    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:25:47.944Z] E0826 09:25:47.943865    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
E0826 09:25:47.943865    3600 watch.go:102] watchAllDir unable to walk dir `d:\xiangmu\Edge-Function\ctoapp\dataconnect`: CreateFile d:\xiangmu\Edge-Function\ctoapp\dataconnect: The system cannot find the file specified.
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:25:47.943865    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\nE0826 09:25:47.943865    3600 watch.go:102] watchAllDir unable to walk dir `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`: CreateFile d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect: The system cannot find the file specified.\n"}}
[debug] [2025-08-26T01:25:57.943Z] E0826 09:25:57.943832    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:25:57.943832    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:26:07.943Z] E0826 09:26:07.944163    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:26:07.944163    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:26:17.945Z] E0826 09:26:17.945784    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:26:17.945784    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:26:27.944Z] E0826 09:26:27.944457    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:26:27.944457    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:26:37.946Z] E0826 09:26:37.946328    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:26:37.946328    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:26:47.946Z] E0826 09:26:47.945090    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:26:47.945090    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:26:57.945Z] E0826 09:26:57.944451    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:26:57.944451    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:27:07.946Z] E0826 09:27:07.946331    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:27:07.946331    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:27:17.945Z] E0826 09:27:17.945098    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:27:17.945098    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:27:27.945Z] E0826 09:27:27.945903    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:27:27.945903    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:27:37.945Z] E0826 09:27:37.945285    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:27:37.945285    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:27:47.944Z] E0826 09:27:47.944971    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
E0826 09:27:47.944971    3600 watch.go:102] watchAllDir unable to walk dir `d:\xiangmu\Edge-Function\ctoapp\dataconnect`: CreateFile d:\xiangmu\Edge-Function\ctoapp\dataconnect: The system cannot find the file specified.
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:27:47.944971    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\nE0826 09:27:47.944971    3600 watch.go:102] watchAllDir unable to walk dir `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`: CreateFile d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect: The system cannot find the file specified.\n"}}
[debug] [2025-08-26T01:27:57.944Z] E0826 09:27:57.945078    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:27:57.945078    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:28:07.946Z] E0826 09:28:07.946682    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:28:07.946682    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:28:17.945Z] E0826 09:28:17.945371    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:28:17.945371    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:28:27.946Z] E0826 09:28:27.946301    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:28:27.946301    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:28:37.945Z] E0826 09:28:37.945804    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:28:37.945804    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:28:47.945Z] E0826 09:28:47.945619    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:28:47.945619    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:28:57.945Z] E0826 09:28:57.946231    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:28:57.946231    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:29:07.945Z] E0826 09:29:07.945856    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:29:07.945856    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:29:17.946Z] E0826 09:29:17.947283    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:29:17.947283    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:29:27.946Z] E0826 09:29:27.947578    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:29:27.947578    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:29:37.946Z] E0826 09:29:37.946127    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:29:37.946127    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:29:47.946Z] E0826 09:29:47.946183    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
E0826 09:29:47.947297    3600 watch.go:102] watchAllDir unable to walk dir `d:\xiangmu\Edge-Function\ctoapp\dataconnect`: CreateFile d:\xiangmu\Edge-Function\ctoapp\dataconnect: The system cannot find the file specified.
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:29:47.946183    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\nE0826 09:29:47.947297    3600 watch.go:102] watchAllDir unable to walk dir `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`: CreateFile d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect: The system cannot find the file specified.\n"}}
[debug] [2025-08-26T01:29:57.946Z] E0826 09:29:57.946393    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:29:57.946393    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:30:07.946Z] E0826 09:30:07.947589    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:30:07.947589    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:30:17.945Z] E0826 09:30:17.946591    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:30:17.946591    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:30:27.946Z] E0826 09:30:27.947317    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:30:27.947317    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:30:37.946Z] E0826 09:30:37.946675    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:30:37.946675    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:30:47.946Z] E0826 09:30:47.947580    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:30:47.947580    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:30:57.946Z] E0826 09:30:57.947360    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:30:57.947360    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:31:07.946Z] E0826 09:31:07.947120    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:31:07.947120    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:31:17.946Z] E0826 09:31:17.947524    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:31:17.947524    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:31:27.947Z] E0826 09:31:27.947364    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:31:27.947364    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:31:37.948Z] E0826 09:31:37.947708    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:31:37.947708    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:31:47.947Z] E0826 09:31:47.947567    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:31:47.947567    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
[debug] [2025-08-26T01:31:47.948Z] E0826 09:31:47.948733    3600 watch.go:102] watchAllDir unable to walk dir `d:\xiangmu\Edge-Function\ctoapp\dataconnect`: CreateFile d:\xiangmu\Edge-Function\ctoapp\dataconnect: The system cannot find the file specified.
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:31:47.948733    3600 watch.go:102] watchAllDir unable to walk dir `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`: CreateFile d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect: The system cannot find the file specified.\n"}}
[debug] [2025-08-26T01:31:57.947Z] E0826 09:31:57.948577    3600 watch.go:31] Failed to load config from "d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect": could not find dataconnect.yaml in `d:\xiangmu\Edge-Function\ctoapp\dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0826 09:31:57.948577    3600 watch.go:31] Failed to load config from \"d:\\\\xiangmu\\\\Edge-Function\\\\ctoapp\\\\dataconnect\": could not find dataconnect.yaml in `d:\\xiangmu\\Edge-Function\\ctoapp\\dataconnect`\n"}}
